# Generated by Django 4.2.7 on 2024-03-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRList',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='temporay',
            name='employee_number',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='EmpCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='absent',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='late',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='remarks',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='temporay',
            name='EmpCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='totalovertime',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='ID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
