# Generated by Django 4.2.7 on 2024-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_qrlist_remove_dailyrecord_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='user_branchname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
